# 통계 기초
NumPy 통계는 정식 통계분석 도구라기보다, 데이터를 빠르게 요약하고 분포를 감 잡기 위한 기초 연산이다.

In [2]:
import numpy as np

## 중심 경향 측도 (Central Tendency)
데이터의 대표적인 중심 값을 나타내는 통계 지표이다.
대표적으로 다음 세 가지를 많이 사용한다.
- 평균(mean) : 모든 값의 합을 데이터 개수로 나눈 값
- 중앙값(median) : 데이터를 정렬했을 때 가운데 위치한 값
- 최빈값(mode) : 가장 많이 등장하는 값

In [5]:
# 학생들의 시험점수
scores = np.array([85, 90, 92, 88, 90, 75, 88, 95, 92, 85, 80, 95, 100, 92, 85])

In [7]:
# 평균(Mean): 데이터의 전체적인 중심을 나타내는 가장 기본적인 통계값
print(f'합계:{np.sum(scores)}')
print(f'데이터 개수:{scores.size}')
print(f'평균:{np.mean(scores)}')

합계:1332
데이터 개수:15
평균:88.8


In [8]:
# 중앙값(Median): 데이터를 정렬했을 때 가운데 위치한 값
# 홀수 -> 가운데 1개 값
# 짝수 -> 가운데 2개 값 평균
# 이상치(outlier)의 영향을 평균보다 덜 받는 특징
print(sorted(scores))
print(f"중앙값 : {np.median(scores)}")

[np.int64(75), np.int64(80), np.int64(85), np.int64(85), np.int64(85), np.int64(88), np.int64(88), np.int64(90), np.int64(90), np.int64(92), np.int64(92), np.int64(92), np.int64(95), np.int64(95), np.int64(100)]
중앙값 : 90.0


In [ ]:
# 최빈값(Mode) : 데이터에서 가장 많이 등장하는 값
print(f'중복 제거한 값: {np.unique(scores)}')
values, counts = np.unique(scores, return_counts=True)
print(values, counts)

max_count = np.max(counts)
# 최대 빈도수와 같은 위치의 값만 선택
vals = values[counts == max_count]
print(f"최빈값: {vals}, 빈도수: {max_count}")

중복 제거한 값: [ 75  80  85  88  90  92  95 100]
[ 75  80  85  88  90  92  95 100] [1 1 3 2 2 3 2 1]
최빈값: [85 92], 빈도수: 3


## 산포 측도
데이터가 평균을 기준으로 얼마나 퍼져 있는지를 나타내는 지표이다.
대표적으로 다음 두 가지를 많이 사용한다.
- 분산(variance)
- 표준편차(standard deviation)

In [11]:
# 분산 : 데이터가 평균에서 얼마나 떨어져있는지 나타내는 값
# 값이 클수록 데이터의 퍼짐 정도가 크다는 의미
# (값-평균)^2의 평균
print(f"분산: { np.mean((scores - np.mean(scores)) ** 2) }")
print(f"분산: { np.var(scores) }")

분산: 36.559999999999995
분산: 36.559999999999995


In [ ]:
# 표준편차 : 분산의 제곱근 
# 데이터가 평균에서 얼마나 퍼져 있는지를 직관적으로 나타냄
print(f'표준편차: { np.sqrt(np.var(scores)) }')
print(f'표준편차: { np.std(scores) }')

표준편차: 6.046486583132389
표준편차: 6.046486583132389


## 모집단 vs 표본
분산과 표준편차는 계산 방식에 따라 두 가지가 있다.
- 모집단: 전체 데이터를 알고 있을 때
- 표본: 일부 데이터로 전체를 추정할 때
  
NumPy에서는 ddof 옵션으로 구분한다. (분산 계산 시 나누는 값을 조정)
- ddof=0: 모집단(default)
- ddof=1: 표본

In [ ]:
# 모집단 기준 계산
print(f'모집단 분산: { np.var(scores, ddof=0)}')
print(f'모집단 표준편차: { np.std(scores, ddof=0)}')
# 표본 기준 계산 (분산 계산 시 나누는 값을 n-1로 처리하므로 값이 약간 더 크게 나온다)
print(f'표본 분산: { np.var(scores, ddof=1)}')
print(f'표본 표준편차: { np.std(scores, ddof=1)}')

모집단 분산: 36.559999999999995
모집단 표준편차: 6.046486583132389
표본 분산: 39.17142857142857
표본 표준편차: 6.258708219067939


## 자주 사용하는 기본 통계 함수
Numpy는 데이터의 기본적인 통계 정보를 빠르게 확인할 수 있는 함수를 제공한다.
이 함수들은 데이터 탐색(EDA)이나 간단한 통계 확인에서 자주 사용 된다.

In [ ]:
# 예시 데이터
values = np.array([12, 25, 8, 45, 33, 17, 29, 41])

# 합계, 최대, 최소
print(np.sum(values))
print(np.min(values))
print(np.max(values))

# 최대값, 최소값의 위치 (인덱스 반환)
print(np.argmin(values))
print(np.argmax(values))

# 범위 : 데이터의 전체 퍼짐 정도 (max - min)
print(np.ptp(values))

210
8
45
2
3
37


## 난수 생성 (Random Data)
Numpy는 다양한 확률 분포 기반의 난수 생성 함수를 제공한다.
대표적으로 다음 분포를 많이 사용한다.
- 정규분포(normal distribution)
- 균등분포(uniform distribution)

데이터 시뮬레이션이나 테스트 데이터 생성에 사용된다.

### 정규 분포
평균을 중심으로 좌우 대칭인 종 모양 분포이다.
Numpy에서는 np.random.normal() 함수로 생성한다.

In [18]:
# random.normal(loc, scale, size)
# loc 평균값, scale 표준편차, size 개수
arr = np.random.normal(0, 1, 100)
arr = np.random.normal(0, 1, (10, 10))
arr

array([[ 1.17185313, -1.13597517, -0.24877247, -0.07913053,  0.3807502 ,
        -1.24674688, -0.28877402,  0.64348273,  1.10554448, -0.72723876],
       [ 0.89474782, -1.32051101, -0.78584415, -0.19444566, -1.71853924,
        -0.85142446,  0.02188769,  1.02353425,  0.45890628, -0.1446628 ],
       [ 0.58901223, -1.21339927, -0.26506925,  1.51276265,  1.21176659,
         1.33738333, -1.17467432,  1.02053748,  1.28005915,  0.04096245],
       [ 0.32939106,  0.4068621 ,  1.20326924,  0.23564905,  0.45130937,
         0.08449978,  1.10839384,  1.78622834,  1.02181201, -0.3921482 ],
       [-0.24524514, -1.03878064, -0.57960226, -0.74931254,  2.04368383,
         0.28804309, -1.95697719,  0.49346996, -0.62743899,  1.10032215],
       [-0.03878531,  1.83401704,  0.10026921, -0.69186629, -0.17797855,
        -1.82930153,  0.1034948 ,  0.3705427 ,  0.28504914,  0.3309111 ],
       [ 0.09552989,  1.1303902 , -0.67875521, -0.55321754, -0.23891238,
        -0.44296201, -0.81981158,  1.55565982

### 표준 정규 분포
np.random.randn() 은 평균 0, 표준편차 1의 정규분포 데이터를 생성한다.

In [20]:
arr = np.random.randn(100)
arr = np.random.randn(5, 20)
arr

array([[-0.00376178,  0.68707867,  1.08771035, -1.21053657, -0.91201965,
        -0.7446934 ,  1.45205863,  0.10639641, -0.18408338, -0.43251686,
         1.42060715, -0.59660343,  1.02618811, -1.24254721, -0.37802419,
         0.18552066,  0.69681135,  0.22113801,  0.46525871, -0.47415791],
       [ 1.45347025, -0.88486589, -0.3587146 ,  0.25158191,  2.22321245,
         1.01341024, -1.18794673,  0.73233401, -0.62813817,  1.63874823,
         0.03042124, -2.6708206 , -0.78463531, -0.42700666, -0.49031731,
        -0.27981593, -0.66407981,  1.03985965, -1.01981708,  0.84763835],
       [-0.17996023, -1.63488573,  1.46135419,  1.62957254,  0.29519428,
        -1.15489557,  1.34805281, -1.02030135,  0.19880811, -0.89404584,
        -0.29250065, -1.52802226, -0.12228502, -0.63668901,  1.22681735,
         0.09474108, -0.04268376, -0.16636197,  1.96988519, -0.28112794],
       [ 1.15994036,  0.05713811, -1.32876877, -0.93048051, -0.12943947,
        -0.33839812, -0.82004223, -0.18917198,  

## 균등 분포
모든 값이 동일한 확률로 발생하는 분포이다.
- np.random.randint() : 지정한 범위에서 정수 난수를 생성한다.

In [21]:
# random.randint(low, high, size)
# low~high 범위의 size 개수 균등 분포 반환
arr = np.random.randint(1, 100, 1000)
arr

array([88, 77, 71,  8, 49,  5, 35, 65, 10, 10, 71, 83, 44, 91, 79, 84, 62,
       51, 92, 44, 48, 37, 54, 88, 12, 13, 86, 36, 47, 13, 68, 21, 86, 98,
       96, 97, 52,  1, 24, 70, 10, 44, 80,  4,  1, 69, 25, 78, 77, 68, 80,
       11, 11, 73, 57, 17, 23, 69, 32, 86, 84, 82, 40,  8, 72, 93,  9, 74,
       98, 49, 17, 72, 31, 59, 24, 94, 65, 47, 75, 57, 80, 35, 48, 77, 31,
       12, 68, 84, 30, 16, 63,  6, 10, 85, 33,  2, 95, 48, 94, 37,  3, 59,
       36, 65, 32, 22, 79, 89, 50, 95,  1, 93, 64, 92, 87, 81, 48, 31, 90,
       41, 75, 63,  4, 28, 98, 14, 14, 72, 91, 69, 65, 65, 73, 57, 46, 60,
       81, 22, 25, 94,  1, 54, 93, 30, 45, 66, 82, 44, 51, 90, 24, 70, 41,
       85, 85, 64, 33, 44, 65, 18, 52, 49, 74, 56, 84, 76, 10, 24, 77, 27,
       65,  8,  6, 95, 69,  1, 57, 18, 27, 40, 30, 43, 74, 14, 54, 53, 26,
       54, 93, 56,  3, 77, 95, 64, 71, 98, 79, 70, 81, 19, 65, 86, 50, 19,
       19, 67, 38, 70, 20, 33, 85,  6, 55, 35, 15, 51, 50, 80, 34, 60,  1,
       78, 74, 34, 21, 76

### np.random.rand() : 0~1 사이의 균등분포 실수 난수를 생성한다.

In [24]:
arr = np.random.rand(10, 10)
arr

array([[0.18526092, 0.44488793, 0.89618057, 0.2983371 , 0.99290136,
        0.09847402, 0.44126743, 0.7869145 , 0.78354055, 0.97257126],
       [0.58496061, 0.69020929, 0.18545244, 0.18312086, 0.65332336,
        0.21614166, 0.73245155, 0.08371019, 0.90842695, 0.75772071],
       [0.46484709, 0.65852509, 0.0032894 , 0.79132693, 0.7411252 ,
        0.74556914, 0.0092044 , 0.47661027, 0.6141561 , 0.46494264],
       [0.3124443 , 0.43858587, 0.92287116, 0.96944956, 0.24983973,
        0.16865518, 0.15256508, 0.37219133, 0.71519697, 0.14495227],
       [0.68691666, 0.9209201 , 0.24530583, 0.9513792 , 0.47966617,
        0.62215499, 0.9614603 , 0.28433969, 0.48068651, 0.18369015],
       [0.04459028, 0.10030472, 0.13508736, 0.77660043, 0.59015049,
        0.70035602, 0.2190127 , 0.44849607, 0.41579367, 0.16593762],
       [0.09999703, 0.1032103 , 0.98180841, 0.4126899 , 0.98054537,
        0.25186417, 0.28791347, 0.21235384, 0.94462609, 0.72067944],
       [0.99652037, 0.89667742, 0.9410304

## seed
난수 생성의 재현성을 위해 seed 값을 고정할 수 있다.

In [53]:
np.random.seed(0)
np.random.rand(2, 3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

## 샘플링 
np.random.choice() 는 기존 데이터에서 무작위로 값을 선택할 때 사용한다.
옵션
- replace=True  : 복원 추출
- replace=False : 비복원 추출

In [ ]:
arr = np.array([10, 3, 5, 7, 8, 9])
np.random.choice(arr)                           # 1개 추출
np.random.choice(arr, size=3)                   # 추출 개수 설정
np.random.choice(arr, size=3, replace=False)    # 중복 불허 비복원 추출

array([3, 7, 8])

In [182]:
# 확률 지정
probs = [0.8, 0.05, 0.05, 0.05, 0.025, 0.025]
np.random.choice(arr, p=probs)

np.int64(10)