# 정렬 (Sorting)
데이터를 **크기 순서대로 정렬** 하는 작업이다.
`np.sort()`를 사용하여 배열을 정렬할 수 있다.

In [2]:
import numpy as np

## 1차원 배열 정렬
`np.sort()`는 배열을 **오름차순**으로 정렬한다.
원본 배열을 변경하지 않고 **정렬 된 새로운 배열**을 반환한다.

In [3]:
arr = np.random.randint(1,11,10)
print(arr)

print(np.sort(arr))
print(arr)

[ 3  2 10  9  5  9  4  7  3  4]
[ 2  3  3  4  4  5  7  9  9 10]
[ 3  2 10  9  5  9  4  7  3  4]


## 역순 정렬
슬라이싱 `[::-1]`을 사용하면 배열을 뒤에서부터 역순으로 뒤집을 수 있다.

In [4]:
np.sort(arr)[::-1]

array([10,  9,  9,  7,  5,  4,  4,  3,  3,  2], dtype=int32)

## 2차원 배열 정렬
2차원 배열에서는 `axis` 옵션으로 **정렬 방향**을 지정할 수 있다.

In [5]:
arr = np.random.randint(1,15,(3,4))
print(arr)

print(np.sort(arr))
print(np.sort(arr, axis=1)) # axis = 1이 기본값 열축
print(np.sort(arr, axis=0)) # axis = 0 행축

[[10 10  1  3]
 [14  6  7  8]
 [14  8 12  3]]
[[ 1  3 10 10]
 [ 6  7  8 14]
 [ 3  8 12 14]]
[[ 1  3 10 10]
 [ 6  7  8 14]
 [ 3  8 12 14]]
[[10  6  1  3]
 [14  8  7  3]
 [14 10 12  8]]


## np.argsort()
배열을 정렬했을 때 **정렬 된 위치(index)**를 반환한다.
이 인덱스를 이용하면 **다른 배열도 같은 기준으로 정렬** 할 수 있다.

In [6]:
arr = np.array([40, 10, 20, 30])
indices = np.argsort(arr)
print(indices)
arr[indices]

[1 2 3 0]


array([10, 20, 30, 40])

## 역순 정렬
내림차순 정렬은 배열에 `-`를 붙여 정렬하면 쉽게 구현할 수 있다.

In [7]:
arr = np.array([40, 10, 20, 30])
indices = np.argsort(-arr)
print(indices)
arr[indices]

[0 3 2 1]


array([40, 30, 20, 10])

## 서로 다른 배열을 같은 기준으로 정렬하기

In [8]:
# 학생 이름, 학생 점수 배열
names = np.array(['홍길동', '신사임당', '이순신', '유관순'])
scores = np.array([90, 30, 50, 70])

# 점수가 높은 순으로 학생 이름 정렬하기
indices = np.argsort(-scores)
print(indices)
print(names[indices])

[0 3 2 1]
['홍길동' '유관순' '이순신' '신사임당']


In [9]:
# 직접 작성해보기 : 우선순위에 따른 작업 정렬
priorities = np.array([3, 1, 2, 5, 4]) # 숫자가 높은 것이 중요도가 높음
tasks = np.array(['Task A', 'Task B', 'Task C', 'Task D', 'Task E'])

indices = np.argsort(-priorities)
print(tasks[indices])

tasks[np.argsort(-priorities)]

['Task D' 'Task E' 'Task A' 'Task C' 'Task B']


array(['Task D', 'Task E', 'Task A', 'Task C', 'Task B'], dtype='<U6')